name: Build Release APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: test secrets
        run: echo secret "${{secrets.KEYALIAS }}" | sed 's/./& /g'
      - name: test secrets
        run: echo secret "${{secrets.KEYPASSWORD }}" | sed 's/./& /g'
      - name: test secrets
        run: echo secret "${{secrets.STOREPASSWORD }}" | sed 's/./& /g'